title: Soroush's Homepage
owner: Mohammad Soroush Esnaashari
email: soroushesnaashari4@gmail.com
description: A full-time Researcher and a part-time Explorer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username: srshesn
github_username: soroushesnaashari
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
